baseurl = "https://www.casualinf.com"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Casual Inference"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Casual Inference" # Set a different text for the header on the home page
  subtitle = "A blog significantly on statistics"
  logo = "img/linreg.png"
  favicon = "img/linreg.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "John SooHwan Lee"
  website = "yourwebsite.com"
  email = "theghks2@gmail.com"
  facebook = "johnswanlee"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "swannyy14"
  #gitlab = "username"
  #bitbucket = "username"
  #twitter = "username"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
